namespace Checklist.Api.Controllers.Features.Supervisor.NaoOk;

public record ItemNaoOkPainelItemDto(
    Guid ChecklistId,
    Guid ChecklistItemId,
    DateTime DataRealizacao,
    Guid SetorOrigemId,
    string SetorOrigemNome,
    string EquipamentoCodigo,
    string EquipamentoDescricao,
    string OperadorNome,
    string OperadorMatricula,
    int Ordem,
    string Descricao,
    string? Instrucao,
    string? Observacao,
    string? ImagemNokBase64,
    string? ImagemNokNomeArquivo,
    string? ImagemNokMimeType,
    string WorkflowStatus,
    Guid? ResponsavelSupervisorId,
    string? ResponsavelNomeCompleto,
    Guid? ResponsavelSetorId,
    string? ResponsavelSetorNome,
    string? ObservacaoAtribuicao,
    string? ObservacaoResponsavel,
    DateTime? DataPrevistaConclusao,
    int PercentualConclusao,
    DateTime? AprovadoEm,
    string? AprovadoPorNomeCompleto,
    DateTime? ConcluidoEm,
    string? ConcluidoPorNomeCompleto,
    List<ItemNaoOkHistoricoEntryDto>? Historico
);
