services:
  db:
    image: postgres:16
    container_name: checklist_db
    environment:
      POSTGRES_DB: checklist
      POSTGRES_USER: checklist
      POSTGRES_PASSWORD: checklist
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: