// <auto-generated />
using System;
using Checklist.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Checklist.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416231304_AddStpInspectionAreasCatalog")]
    partial class AddStpInspectionAreasCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModeloFechamentoMensal")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId", "Nome")
                        .IsUnique();

                    b.ToTable("CategoriasEquipamento");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssinaturaOperadorBase64")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("SetorId", "EquipamentoId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistEnviado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("OperadorMatricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperadorNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("ChecklistsEnviados");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ImagemNokBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemNokMimeType")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ImagemNokNomeArquivo")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ChecklistItens");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AprovadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AprovadoPorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistItemId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ConcluidoPorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPrevistaConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObservacaoAtribuicao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ObservacaoResponsavel")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PercentualConclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ResponsavelSetorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ResponsavelSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorSupervisorId");

                    b.HasIndex("ChecklistItemId")
                        .IsUnique();

                    b.HasIndex("ConcluidoPorSupervisorId");

                    b.HasIndex("ResponsavelSetorId");

                    b.HasIndex("ResponsavelSupervisorId");

                    b.ToTable("ChecklistItensAcoes");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemAcaoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistItemAcaoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CriadoPorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemAcaoId");

                    b.HasIndex("CriadoPorSupervisorId");

                    b.ToTable("ChecklistItensAcoesHistorico");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("CategoriaId", "Ordem");

                    b.ToTable("ChecklistItensTemplate");
                });

            modelBuilder.Entity("Checklist.Api.Models.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("QrId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("QrId")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FechadoPorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashPdfSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivoPdf")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<byte[]>("PdfConteudo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("QuantidadeChecklists")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TemplateVersao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("FechadoPorSupervisorId");

                    b.HasIndex("SetorId", "EquipamentoId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("FechamentosChecklistMensais");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensalChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FechamentoChecklistMensalId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("FechamentoChecklistMensalId", "ChecklistId")
                        .IsUnique();

                    b.ToTable("FechamentosChecklistMensaisChecklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("Checklist.Api.Models.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AreaInspecaoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssinadoInspetorEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AssinadoResponsavelPresenteEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssinaturaInspetorBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssinaturaResponsavelPresenteBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AtosInsegurosObservados")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ComportamentosPreventivosObservados")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("CondicoesInsegurasConstatadas")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InspetorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponsavelPresenteCargo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ResponsavelPresenteNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorInspecionadoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AreaInspecaoId");

                    b.HasIndex("InspetorSupervisorId");

                    b.HasIndex("SetorInspecionadoId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("SetorId", "DataReferencia");

                    b.ToTable("StpAreaChecklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateItemId");

                    b.HasIndex("ChecklistId", "Ordem")
                        .IsUnique();

                    b.ToTable("StpAreaChecklistItens");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId", "Codigo")
                        .IsUnique();

                    b.ToTable("StpAreaChecklistTemplates");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Ordem")
                        .IsUnique();

                    b.ToTable("StpAreaChecklistTemplateItens");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaInspecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid>("ResponsavelSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelSupervisorId");

                    b.HasIndex("SetorId", "Nome")
                        .IsUnique();

                    b.ToTable("StpAreasInspecao");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("ForceChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ramal")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("UsuariosSupervisores");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisorModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Modulo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioSupervisorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSupervisorId", "Modulo")
                        .IsUnique();

                    b.ToTable("UsuariosSupervisoresModulos");
                });

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Operador");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistEnviado", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItem", b =>
                {
                    b.HasOne("Checklist.Api.Models.Checklist", "Checklist")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.ChecklistItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemAcao", b =>
                {
                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "AprovadoPorSupervisor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.ChecklistItem", "ChecklistItem")
                        .WithOne("Acao")
                        .HasForeignKey("Checklist.Api.Models.ChecklistItemAcao", "ChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "ConcluidoPorSupervisor")
                        .WithMany()
                        .HasForeignKey("ConcluidoPorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Checklist.Api.Models.Setor", "ResponsavelSetor")
                        .WithMany()
                        .HasForeignKey("ResponsavelSetorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "ResponsavelSupervisor")
                        .WithMany()
                        .HasForeignKey("ResponsavelSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprovadoPorSupervisor");

                    b.Navigation("ChecklistItem");

                    b.Navigation("ConcluidoPorSupervisor");

                    b.Navigation("ResponsavelSetor");

                    b.Navigation("ResponsavelSupervisor");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemAcaoHistorico", b =>
                {
                    b.HasOne("Checklist.Api.Models.ChecklistItemAcao", "ChecklistItemAcao")
                        .WithMany("Historico")
                        .HasForeignKey("ChecklistItemAcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CIAHistorico_Acao");

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "CriadoPorSupervisor")
                        .WithMany()
                        .HasForeignKey("CriadoPorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CIAHistorico_Supervisor");

                    b.Navigation("ChecklistItemAcao");

                    b.Navigation("CriadoPorSupervisor");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.HasOne("Checklist.Api.Models.CategoriaEquipamento", "Categoria")
                        .WithMany("ChecklistItensTemplate")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.Equipamento", b =>
                {
                    b.HasOne("Checklist.Api.Models.CategoriaEquipamento", "Categoria")
                        .WithMany("Equipamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "FechadoPorSupervisor")
                        .WithMany()
                        .HasForeignKey("FechadoPorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("FechadoPorSupervisor");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensalChecklist", b =>
                {
                    b.HasOne("Checklist.Api.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.FechamentoChecklistMensal", "FechamentoChecklistMensal")
                        .WithMany("Checklists")
                        .HasForeignKey("FechamentoChecklistMensalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("FechamentoChecklistMensal");
                });

            modelBuilder.Entity("Checklist.Api.Models.Operador", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklist", b =>
                {
                    b.HasOne("Checklist.Api.Models.StpAreaInspecao", "AreaInspecao")
                        .WithMany()
                        .HasForeignKey("AreaInspecaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "InspetorSupervisor")
                        .WithMany()
                        .HasForeignKey("InspetorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "SetorInspecionado")
                        .WithMany()
                        .HasForeignKey("SetorInspecionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.StpAreaChecklistTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaInspecao");

                    b.Navigation("InspetorSupervisor");

                    b.Navigation("Setor");

                    b.Navigation("SetorInspecionado");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistItem", b =>
                {
                    b.HasOne("Checklist.Api.Models.StpAreaChecklist", "Checklist")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.StpAreaChecklistTemplateItem", "TemplateItem")
                        .WithMany()
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistTemplate", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistTemplateItem", b =>
                {
                    b.HasOne("Checklist.Api.Models.StpAreaChecklistTemplate", "Template")
                        .WithMany("Itens")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaInspecao", b =>
                {
                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "ResponsavelSupervisor")
                        .WithMany()
                        .HasForeignKey("ResponsavelSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResponsavelSupervisor");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisor", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisorModulo", b =>
                {
                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "UsuarioSupervisor")
                        .WithMany("Modulos")
                        .HasForeignKey("UsuarioSupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioSupervisor");
                });

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.Navigation("ChecklistItensTemplate");

                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItem", b =>
                {
                    b.Navigation("Acao");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemAcao", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.Navigation("Checklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklist", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Checklist.Api.Models.StpAreaChecklistTemplate", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisor", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
