// <auto-generated />
using System;
using Checklist.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Checklist.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331002238_AddCategoryMonthlyModels")]
    partial class AddCategoryMonthlyModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModeloFechamentoMensal")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId", "Nome")
                        .IsUnique();

                    b.ToTable("CategoriasEquipamento");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssinaturaOperadorBase64")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("SetorId", "EquipamentoId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistEnviado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("OperadorMatricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperadorNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("ChecklistsEnviados");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ChecklistItens");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Instrucao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("CategoriaId", "Ordem");

                    b.ToTable("ChecklistItensTemplate");
                });

            modelBuilder.Entity("Checklist.Api.Models.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("QrId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("QrId")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FechadoPorSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashPdfSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivoPdf")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<byte[]>("PdfConteudo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("QuantidadeChecklists")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TemplateVersao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("FechadoPorSupervisorId");

                    b.HasIndex("SetorId", "EquipamentoId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("FechamentosChecklistMensais");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensalChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FechamentoChecklistMensalId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("FechamentoChecklistMensalId", "ChecklistId")
                        .IsUnique();

                    b.ToTable("FechamentosChecklistMensaisChecklists");
                });

            modelBuilder.Entity("Checklist.Api.Models.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("Checklist.Api.Models.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("ForceChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ramal")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("UsuariosSupervisores");
                });

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Operador");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistEnviado", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItem", b =>
                {
                    b.HasOne("Checklist.Api.Models.Checklist", "Checklist")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.ChecklistItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Checklist.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.HasOne("Checklist.Api.Models.CategoriaEquipamento", "Categoria")
                        .WithMany("ChecklistItensTemplate")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.Equipamento", b =>
                {
                    b.HasOne("Checklist.Api.Models.CategoriaEquipamento", "Categoria")
                        .WithMany("Equipamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.HasOne("Checklist.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.UsuarioSupervisor", "FechadoPorSupervisor")
                        .WithMany()
                        .HasForeignKey("FechadoPorSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("FechadoPorSupervisor");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensalChecklist", b =>
                {
                    b.HasOne("Checklist.Api.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checklist.Api.Models.FechamentoChecklistMensal", "FechamentoChecklistMensal")
                        .WithMany("Checklists")
                        .HasForeignKey("FechamentoChecklistMensalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("FechamentoChecklistMensal");
                });

            modelBuilder.Entity("Checklist.Api.Models.Operador", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.UsuarioSupervisor", b =>
                {
                    b.HasOne("Checklist.Api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Checklist.Api.Models.CategoriaEquipamento", b =>
                {
                    b.Navigation("ChecklistItensTemplate");

                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("Checklist.Api.Models.Checklist", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Checklist.Api.Models.FechamentoChecklistMensal", b =>
                {
                    b.Navigation("Checklists");
                });
#pragma warning restore 612, 618
        }
    }
}
